version: "3"

services:
    redis:
        image: redis:6-alpine
    db:
        image: postgis/postgis:11-3.0-alpine
        environment:
            POSTGRES_PASSWORD: password
        volumes:
            - ./misc/dbdata:/var/lib/postgresql/data:delegated

    web:
        command: ./manage.py runserver 0.0.0.0:8000
        image: "web"
        build: .
        volumes:
            - .:/code:cached
            - ./misc/importdata:/importdata

        ports:
            - "8000:8000"
        depends_on:
            - db
            - redis
            - manage
        environment:
            IN_DOCKER: 1

    manage:
        image: web
        build: .
        command: bash -c "./manage.py makemigrations && ./manage.py migrate --noinput"
        volumes:
            - .:/code
            - ./misc/importdata:/importdata
        depends_on:
            - db
        environment:
            IN_DOCKER: 1
