[tool.poetry]
name = "apirechtegewalt"
version = "0.0.0"
description = ""
authors = []

[tool.poetry.dependencies]
python = ">=3.8"
django = ">=3.1"
djangorestframework="^3.10.0"
djangorestframework-gis="^0.15.0"
django-filter="*"
django-extensions = "*"
django-dotenv = "*"
django-redis = "*"
django-cors-headers = "*"
psycopg2-binary = "*"
sentry-sdk = "*"
uwsgi = "*"
whitenoise = "*"
dataset="*"
tqdm="*"
markdown="*"

[tool.poetry.dev-dependencies]
werkzeug = "*" # used for local development server
pytest = "*"
pytest-cov = "*"
black = {version = "*", allow-prereleases = true, python = ">=3.6"}

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
